---
- hosts: all
  become: True
  
  tasks:
    - name: install docker
      yum:
        name: docker 
        state: installed 
        update_cache: yes
        validate_certs: yes
    - name : start and enable docker service 
      service:
        name: docker 
        state: started
        enabled: yes
   

